

a = Analysis(
    ['zapret_tester.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('1.ico', '.'),
        ('on.png', '.'),
        ('off.png', '.'),
        ('zapret', 'zapret'),
    ],
    hidden_imports = [
    'ping3',
    'ping3.exceptions',
    'pystray',
    'pystray._win32',
    'PIL',
    'PIL.Image',
    'PIL.ImageDraw',
    'PIL.ImageTk',
    'PIL.ImageFilter',
    'PIL._tkinter_finder',
    'tkinter',
    'tkinter.ttk',
    'tkinter.font',
    'requests',
    'urllib3',
    'psutil',
    'psutil._psutil_windows',
    'queue',
    'math',
    'json',
    'winreg',
    'ctypes',
    'subprocess',
    'threading',
    'pathlib',
    'time',
    'os',
    'sys',
    'socket',
    'select',
],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ZapretTester',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='1.ico',
    version='version.txt' if os.path.exists('version.txt') else None,
    uac_admin=True,
)